/*
 * generated by Xtext 2.40.0
 */
package org.example.dsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class ResumeDslUiModule extends AbstractResumeDslUiModule {

	public ResumeDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
