/*
 * generated by Xtext 2.40.0
 */
package org.example.dsl.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;
import org.xtext.example.CVdsl.ui.internal.CVdslActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class ResumeDslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(CVdslActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		CVdslActivator activator = CVdslActivator.getInstance();
		return activator != null ? activator.getInjector(CVdslActivator.ORG_EXAMPLE_DSL_RESUMEDSL) : null;
	}

}
