/*
 * generated by Xtext 2.40.0
 */
package org.example.dsl;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class ResumeDslStandaloneSetup extends ResumeDslStandaloneSetupGenerated {

	public static void doSetup() {
		new ResumeDslStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
