/**
 * generated by Xtext 2.40.0
 */
package org.example.dsl.resumeDsl.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.example.dsl.resumeDsl.Project;
import org.example.dsl.resumeDsl.ResumeDslPackage;
import org.example.dsl.resumeDsl.StringList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Project</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.example.dsl.resumeDsl.impl.ProjectImpl#getTitle <em>Title</em>}</li>
 *   <li>{@link org.example.dsl.resumeDsl.impl.ProjectImpl#getDescription <em>Description</em>}</li>
 *   <li>{@link org.example.dsl.resumeDsl.impl.ProjectImpl#getTechnologies <em>Technologies</em>}</li>
 *   <li>{@link org.example.dsl.resumeDsl.impl.ProjectImpl#getLink <em>Link</em>}</li>
 *   <li>{@link org.example.dsl.resumeDsl.impl.ProjectImpl#getTags <em>Tags</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ProjectImpl extends MinimalEObjectImpl.Container implements Project
{
  /**
   * The default value of the '{@link #getTitle() <em>Title</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTitle()
   * @generated
   * @ordered
   */
  protected static final String TITLE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getTitle() <em>Title</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTitle()
   * @generated
   * @ordered
   */
  protected String title = TITLE_EDEFAULT;

  /**
   * The cached value of the '{@link #getDescription() <em>Description</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDescription()
   * @generated
   * @ordered
   */
  protected StringList description;

  /**
   * The cached value of the '{@link #getTechnologies() <em>Technologies</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTechnologies()
   * @generated
   * @ordered
   */
  protected StringList technologies;

  /**
   * The default value of the '{@link #getLink() <em>Link</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLink()
   * @generated
   * @ordered
   */
  protected static final String LINK_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getLink() <em>Link</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLink()
   * @generated
   * @ordered
   */
  protected String link = LINK_EDEFAULT;

  /**
   * The cached value of the '{@link #getTags() <em>Tags</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTags()
   * @generated
   * @ordered
   */
  protected StringList tags;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ProjectImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return ResumeDslPackage.Literals.PROJECT;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getTitle()
  {
    return title;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setTitle(String newTitle)
  {
    String oldTitle = title;
    title = newTitle;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ResumeDslPackage.PROJECT__TITLE, oldTitle, title));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public StringList getDescription()
  {
    return description;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetDescription(StringList newDescription, NotificationChain msgs)
  {
    StringList oldDescription = description;
    description = newDescription;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, ResumeDslPackage.PROJECT__DESCRIPTION, oldDescription, newDescription);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setDescription(StringList newDescription)
  {
    if (newDescription != description)
    {
      NotificationChain msgs = null;
      if (description != null)
        msgs = ((InternalEObject)description).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - ResumeDslPackage.PROJECT__DESCRIPTION, null, msgs);
      if (newDescription != null)
        msgs = ((InternalEObject)newDescription).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - ResumeDslPackage.PROJECT__DESCRIPTION, null, msgs);
      msgs = basicSetDescription(newDescription, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ResumeDslPackage.PROJECT__DESCRIPTION, newDescription, newDescription));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public StringList getTechnologies()
  {
    return technologies;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetTechnologies(StringList newTechnologies, NotificationChain msgs)
  {
    StringList oldTechnologies = technologies;
    technologies = newTechnologies;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, ResumeDslPackage.PROJECT__TECHNOLOGIES, oldTechnologies, newTechnologies);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setTechnologies(StringList newTechnologies)
  {
    if (newTechnologies != technologies)
    {
      NotificationChain msgs = null;
      if (technologies != null)
        msgs = ((InternalEObject)technologies).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - ResumeDslPackage.PROJECT__TECHNOLOGIES, null, msgs);
      if (newTechnologies != null)
        msgs = ((InternalEObject)newTechnologies).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - ResumeDslPackage.PROJECT__TECHNOLOGIES, null, msgs);
      msgs = basicSetTechnologies(newTechnologies, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ResumeDslPackage.PROJECT__TECHNOLOGIES, newTechnologies, newTechnologies));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getLink()
  {
    return link;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setLink(String newLink)
  {
    String oldLink = link;
    link = newLink;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ResumeDslPackage.PROJECT__LINK, oldLink, link));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public StringList getTags()
  {
    return tags;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetTags(StringList newTags, NotificationChain msgs)
  {
    StringList oldTags = tags;
    tags = newTags;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, ResumeDslPackage.PROJECT__TAGS, oldTags, newTags);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setTags(StringList newTags)
  {
    if (newTags != tags)
    {
      NotificationChain msgs = null;
      if (tags != null)
        msgs = ((InternalEObject)tags).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - ResumeDslPackage.PROJECT__TAGS, null, msgs);
      if (newTags != null)
        msgs = ((InternalEObject)newTags).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - ResumeDslPackage.PROJECT__TAGS, null, msgs);
      msgs = basicSetTags(newTags, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ResumeDslPackage.PROJECT__TAGS, newTags, newTags));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case ResumeDslPackage.PROJECT__DESCRIPTION:
        return basicSetDescription(null, msgs);
      case ResumeDslPackage.PROJECT__TECHNOLOGIES:
        return basicSetTechnologies(null, msgs);
      case ResumeDslPackage.PROJECT__TAGS:
        return basicSetTags(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case ResumeDslPackage.PROJECT__TITLE:
        return getTitle();
      case ResumeDslPackage.PROJECT__DESCRIPTION:
        return getDescription();
      case ResumeDslPackage.PROJECT__TECHNOLOGIES:
        return getTechnologies();
      case ResumeDslPackage.PROJECT__LINK:
        return getLink();
      case ResumeDslPackage.PROJECT__TAGS:
        return getTags();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case ResumeDslPackage.PROJECT__TITLE:
        setTitle((String)newValue);
        return;
      case ResumeDslPackage.PROJECT__DESCRIPTION:
        setDescription((StringList)newValue);
        return;
      case ResumeDslPackage.PROJECT__TECHNOLOGIES:
        setTechnologies((StringList)newValue);
        return;
      case ResumeDslPackage.PROJECT__LINK:
        setLink((String)newValue);
        return;
      case ResumeDslPackage.PROJECT__TAGS:
        setTags((StringList)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case ResumeDslPackage.PROJECT__TITLE:
        setTitle(TITLE_EDEFAULT);
        return;
      case ResumeDslPackage.PROJECT__DESCRIPTION:
        setDescription((StringList)null);
        return;
      case ResumeDslPackage.PROJECT__TECHNOLOGIES:
        setTechnologies((StringList)null);
        return;
      case ResumeDslPackage.PROJECT__LINK:
        setLink(LINK_EDEFAULT);
        return;
      case ResumeDslPackage.PROJECT__TAGS:
        setTags((StringList)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case ResumeDslPackage.PROJECT__TITLE:
        return TITLE_EDEFAULT == null ? title != null : !TITLE_EDEFAULT.equals(title);
      case ResumeDslPackage.PROJECT__DESCRIPTION:
        return description != null;
      case ResumeDslPackage.PROJECT__TECHNOLOGIES:
        return technologies != null;
      case ResumeDslPackage.PROJECT__LINK:
        return LINK_EDEFAULT == null ? link != null : !LINK_EDEFAULT.equals(link);
      case ResumeDslPackage.PROJECT__TAGS:
        return tags != null;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (title: ");
    result.append(title);
    result.append(", link: ");
    result.append(link);
    result.append(')');
    return result.toString();
  }

} //ProjectImpl
