/**
 * generated by Xtext 2.40.0
 */
package org.example.dsl.resumeDsl.impl;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EDataType;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;

import org.eclipse.emf.ecore.impl.EFactoryImpl;

import org.eclipse.emf.ecore.plugin.EcorePlugin;

import org.example.dsl.resumeDsl.*;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Factory</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class ResumeDslFactoryImpl extends EFactoryImpl implements ResumeDslFactory
{
  /**
   * Creates the default factory implementation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static ResumeDslFactory init()
  {
    try
    {
      ResumeDslFactory theResumeDslFactory = (ResumeDslFactory)EPackage.Registry.INSTANCE.getEFactory(ResumeDslPackage.eNS_URI);
      if (theResumeDslFactory != null)
      {
        return theResumeDslFactory;
      }
    }
    catch (Exception exception)
    {
      EcorePlugin.INSTANCE.log(exception);
    }
    return new ResumeDslFactoryImpl();
  }

  /**
   * Creates an instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ResumeDslFactoryImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EObject create(EClass eClass)
  {
    switch (eClass.getClassifierID())
    {
      case ResumeDslPackage.PROFILE: return createProfile();
      case ResumeDslPackage.METADATA: return createMetadata();
      case ResumeDslPackage.USERDATA: return createUserdata();
      case ResumeDslPackage.SECTION: return createSection();
      case ResumeDslPackage.EXPERIENCE: return createExperience();
      case ResumeDslPackage.JOB: return createJob();
      case ResumeDslPackage.PROJECTS: return createProjects();
      case ResumeDslPackage.PROJECT: return createProject();
      case ResumeDslPackage.EDUCATION: return createEducation();
      case ResumeDslPackage.DEGREE: return createDegree();
      case ResumeDslPackage.SKILLS: return createSkills();
      case ResumeDslPackage.SKILL: return createSkill();
      case ResumeDslPackage.INTERESTS: return createInterests();
      case ResumeDslPackage.LANGUAGES: return createLanguages();
      case ResumeDslPackage.CUSTOMIZATION: return createCustomization();
      case ResumeDslPackage.RULE: return createRule();
      case ResumeDslPackage.FILTER: return createFilter();
      case ResumeDslPackage.GENERAL_FILTER: return createGeneralFilter();
      case ResumeDslPackage.TEMPORAL_FILTER: return createTemporalFilter();
      case ResumeDslPackage.STRING_LIST: return createStringList();
      default:
        throw new IllegalArgumentException("The class '" + eClass.getName() + "' is not a valid classifier");
    }
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object createFromString(EDataType eDataType, String initialValue)
  {
    switch (eDataType.getClassifierID())
    {
      case ResumeDslPackage.SECTION_TYPE:
        return createSectionTypeFromString(eDataType, initialValue);
      default:
        throw new IllegalArgumentException("The datatype '" + eDataType.getName() + "' is not a valid classifier");
    }
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String convertToString(EDataType eDataType, Object instanceValue)
  {
    switch (eDataType.getClassifierID())
    {
      case ResumeDslPackage.SECTION_TYPE:
        return convertSectionTypeToString(eDataType, instanceValue);
      default:
        throw new IllegalArgumentException("The datatype '" + eDataType.getName() + "' is not a valid classifier");
    }
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Profile createProfile()
  {
    ProfileImpl profile = new ProfileImpl();
    return profile;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Metadata createMetadata()
  {
    MetadataImpl metadata = new MetadataImpl();
    return metadata;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Userdata createUserdata()
  {
    UserdataImpl userdata = new UserdataImpl();
    return userdata;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Section createSection()
  {
    SectionImpl section = new SectionImpl();
    return section;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Experience createExperience()
  {
    ExperienceImpl experience = new ExperienceImpl();
    return experience;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Job createJob()
  {
    JobImpl job = new JobImpl();
    return job;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Projects createProjects()
  {
    ProjectsImpl projects = new ProjectsImpl();
    return projects;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Project createProject()
  {
    ProjectImpl project = new ProjectImpl();
    return project;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Education createEducation()
  {
    EducationImpl education = new EducationImpl();
    return education;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Degree createDegree()
  {
    DegreeImpl degree = new DegreeImpl();
    return degree;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Skills createSkills()
  {
    SkillsImpl skills = new SkillsImpl();
    return skills;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Skill createSkill()
  {
    SkillImpl skill = new SkillImpl();
    return skill;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Interests createInterests()
  {
    InterestsImpl interests = new InterestsImpl();
    return interests;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Languages createLanguages()
  {
    LanguagesImpl languages = new LanguagesImpl();
    return languages;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Customization createCustomization()
  {
    CustomizationImpl customization = new CustomizationImpl();
    return customization;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Rule createRule()
  {
    RuleImpl rule = new RuleImpl();
    return rule;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Filter createFilter()
  {
    FilterImpl filter = new FilterImpl();
    return filter;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public GeneralFilter createGeneralFilter()
  {
    GeneralFilterImpl generalFilter = new GeneralFilterImpl();
    return generalFilter;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public TemporalFilter createTemporalFilter()
  {
    TemporalFilterImpl temporalFilter = new TemporalFilterImpl();
    return temporalFilter;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public StringList createStringList()
  {
    StringListImpl stringList = new StringListImpl();
    return stringList;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public SectionType createSectionTypeFromString(EDataType eDataType, String initialValue)
  {
    SectionType result = SectionType.get(initialValue);
    if (result == null) throw new IllegalArgumentException("The value '" + initialValue + "' is not a valid enumerator of '" + eDataType.getName() + "'");
    return result;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String convertSectionTypeToString(EDataType eDataType, Object instanceValue)
  {
    return instanceValue == null ? null : instanceValue.toString();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ResumeDslPackage getResumeDslPackage()
  {
    return (ResumeDslPackage)getEPackage();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @deprecated
   * @generated
   */
  @Deprecated
  public static ResumeDslPackage getPackage()
  {
    return ResumeDslPackage.eINSTANCE;
  }

} //ResumeDslFactoryImpl
