version: "3.8"

services:
  python-microservice:
    build: ./python-microservice
    ports:
      - "8000:8000"
    networks:
      - cv-network
    # Le damos un nombre de host interno para que Java lo encuentre
    hostname: python-service

# 2. El nuevo orquestador de Java
  java-microservice:
    build:
      context: ./java-microservice
    ports:
      - "8081:8081"
    networks:
      - cv-network
    depends_on:
      - python-microservice 
    environment:
      # Le pasamos a Java la URL interna de Python por variable de entorno
      - PYTHON_SERVICE_URL=http://python-service:8000/generate-pdf
      - SERVER_PORT=8081

# Definimos la red privada que los aísla del exterior
networks:
  cv-network:
    driver: bridge