version: "3.8"

services:
  python-microservice:
    build: ./python-microservice
    ports:
      - "8000:8000"
    networks:
      - app-network

  

volumes:
  db_data:

networks:
  app-network:
    driver: bridge