/*
 * generated by Xtext 2.40.0
 */
package org.example.dsl.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.example.CVdsl.ui.internal.CVdslActivator;

public class ResumeDslUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return CVdslActivator.getInstance().getInjector("org.example.dsl.ResumeDsl");
	}

}
