/*
 * generated by Xtext 2.41.0
 */
package org.xtext.example.resume.web;


/**
 * Use this class to register additional components to be used within the web application.
 */
public class ResumeWebModule extends AbstractResumeWebModule {
}
