/*
 * generated by Xtext 2.41.0
 */
package org.xtext.example.resume.web;

import java.io.IOException;
import java.net.InetSocketAddress;
import java.util.EnumSet;

import jakarta.servlet.DispatcherType;
import jakarta.servlet.Filter;
import jakarta.servlet.FilterChain;
import jakarta.servlet.FilterConfig;
import jakarta.servlet.ServletException;
import jakarta.servlet.ServletRequest;
import jakarta.servlet.ServletResponse;
import jakarta.servlet.http.HttpServletResponse;

import org.eclipse.jetty.annotations.AnnotationConfiguration;
import org.eclipse.jetty.server.Server;
import org.eclipse.jetty.servlet.FilterHolder;
import org.eclipse.jetty.webapp.Configuration;
import org.eclipse.jetty.webapp.MetaInfConfiguration;
import org.eclipse.jetty.webapp.WebAppConfiguration;
import org.eclipse.jetty.webapp.WebAppContext;
import org.eclipse.jetty.webapp.WebInfConfiguration;
import org.eclipse.jetty.webapp.WebXmlConfiguration;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class ServerLauncher {

    private static final Logger LOG = LoggerFactory.getLogger(ServerLauncher.class);

    public static class CorsFilter implements Filter {
        @Override public void init(FilterConfig cfg) {}
        @Override public void destroy() {}
        @Override
        public void doFilter(ServletRequest req, ServletResponse res, FilterChain chain)
                throws IOException, ServletException {
            HttpServletResponse http = (HttpServletResponse) res;
            http.setHeader("Access-Control-Allow-Origin",  "*");
            http.setHeader("Access-Control-Allow-Methods", "GET, POST, OPTIONS, HEAD");
            http.setHeader("Access-Control-Allow-Headers",
                "Content-Type, Accept, Origin, X-Requested-With");
            chain.doFilter(req, res);
        }
    }

    public static void main(String[] args) {
        Server server = new Server(new InetSocketAddress("localhost", 8080));
        WebAppContext ctx = new WebAppContext();
        ctx.setResourceBase("WebRoot");
        ctx.setWelcomeFiles(new String[] {"index.html"});
        ctx.setContextPath("/");
        ctx.setConfigurations(new Configuration[] {
            new AnnotationConfiguration(),
            new WebXmlConfiguration(),
            new WebInfConfiguration(),
            new MetaInfConfiguration(),
            new WebAppConfiguration()
        });
        ctx.setAttribute(MetaInfConfiguration.CONTAINER_JAR_PATTERN,
            ".*/org\\.xtext\\.example\\.resume\\.web/.*,.*\\.jar");
        ctx.setInitParameter("org.eclipse.jetty.servlet.Default.useFileMappedBuffer", "false");

        // Inline CORS filter — no extra dependencies needed
        ctx.addFilter(new FilterHolder(new CorsFilter()), "/*",
            EnumSet.of(DispatcherType.REQUEST, DispatcherType.ASYNC));

        server.setHandler(ctx);
        try {
            server.start();
            LOG.info("Server started " + server.getURI() + "...");
            new Thread() {
                public void run() {
                    try {
                        LOG.info("Press enter to stop the server...");
                        int key = System.in.read();
                        if (key != -1) {
                            server.stop();
                        } else {
                            LOG.warn("Console input not available. Cancel process manually.");
                        }
                    } catch (Exception e) {
                        LOG.warn(e.getMessage());
                    }
                }
            }.start();
            server.join();
        } catch (Exception exception) {
            LOG.warn(exception.getMessage());
            System.exit(1);
        }
    }
}