/*
 * generated by Xtext 2.41.0
 */
package org.xtext.example.resume.web;

import org.eclipse.xtext.web.server.DefaultWebModule;

/**
 * Manual modifications go to {@link ResumeWebModule}.
 */
@SuppressWarnings("all")
public abstract class AbstractResumeWebModule extends DefaultWebModule {

}
