/*
 * generated by Xtext 2.40.0
 */
package org.example.dsl.serializer;

import com.google.inject.Inject;
import java.util.Set;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Parameter;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.serializer.ISerializationContext;
import org.eclipse.xtext.serializer.acceptor.SequenceFeeder;
import org.eclipse.xtext.serializer.sequencer.AbstractDelegatingSemanticSequencer;
import org.eclipse.xtext.serializer.sequencer.ITransientValueService.ValueTransient;
import org.example.dsl.resumeDsl.Customization;
import org.example.dsl.resumeDsl.Degree;
import org.example.dsl.resumeDsl.Education;
import org.example.dsl.resumeDsl.Experience;
import org.example.dsl.resumeDsl.GeneralFilter;
import org.example.dsl.resumeDsl.Interests;
import org.example.dsl.resumeDsl.Job;
import org.example.dsl.resumeDsl.Languages;
import org.example.dsl.resumeDsl.Metadata;
import org.example.dsl.resumeDsl.Profile;
import org.example.dsl.resumeDsl.Project;
import org.example.dsl.resumeDsl.Projects;
import org.example.dsl.resumeDsl.ResumeDslPackage;
import org.example.dsl.resumeDsl.Rule;
import org.example.dsl.resumeDsl.Skill;
import org.example.dsl.resumeDsl.Skills;
import org.example.dsl.resumeDsl.StringList;
import org.example.dsl.resumeDsl.TemporalFilter;
import org.example.dsl.resumeDsl.Userdata;
import org.example.dsl.services.ResumeDslGrammarAccess;

@SuppressWarnings("all")
public class ResumeDslSemanticSequencer extends AbstractDelegatingSemanticSequencer {

	@Inject
	private ResumeDslGrammarAccess grammarAccess;
	
	@Override
	public void sequence(ISerializationContext context, EObject semanticObject) {
		EPackage epackage = semanticObject.eClass().getEPackage();
		ParserRule rule = context.getParserRule();
		Action action = context.getAssignedAction();
		Set<Parameter> parameters = context.getEnabledBooleanParameters();
		if (epackage == ResumeDslPackage.eINSTANCE)
			switch (semanticObject.eClass().getClassifierID()) {
			case ResumeDslPackage.CUSTOMIZATION:
				sequence_Customization(context, (Customization) semanticObject); 
				return; 
			case ResumeDslPackage.DEGREE:
				sequence_Degree(context, (Degree) semanticObject); 
				return; 
			case ResumeDslPackage.EDUCATION:
				sequence_Education(context, (Education) semanticObject); 
				return; 
			case ResumeDslPackage.EXPERIENCE:
				sequence_Experience(context, (Experience) semanticObject); 
				return; 
			case ResumeDslPackage.GENERAL_FILTER:
				sequence_GeneralFilter(context, (GeneralFilter) semanticObject); 
				return; 
			case ResumeDslPackage.INTERESTS:
				sequence_Interests(context, (Interests) semanticObject); 
				return; 
			case ResumeDslPackage.JOB:
				sequence_Job(context, (Job) semanticObject); 
				return; 
			case ResumeDslPackage.LANGUAGES:
				sequence_Languages(context, (Languages) semanticObject); 
				return; 
			case ResumeDslPackage.METADATA:
				sequence_Metadata(context, (Metadata) semanticObject); 
				return; 
			case ResumeDslPackage.PROFILE:
				sequence_Profile(context, (Profile) semanticObject); 
				return; 
			case ResumeDslPackage.PROJECT:
				sequence_Project(context, (Project) semanticObject); 
				return; 
			case ResumeDslPackage.PROJECTS:
				sequence_Projects(context, (Projects) semanticObject); 
				return; 
			case ResumeDslPackage.RULE:
				sequence_Rule(context, (Rule) semanticObject); 
				return; 
			case ResumeDslPackage.SKILL:
				sequence_Skill(context, (Skill) semanticObject); 
				return; 
			case ResumeDslPackage.SKILLS:
				sequence_Skills(context, (Skills) semanticObject); 
				return; 
			case ResumeDslPackage.STRING_LIST:
				sequence_StringList(context, (StringList) semanticObject); 
				return; 
			case ResumeDslPackage.TEMPORAL_FILTER:
				sequence_TemporalFilter(context, (TemporalFilter) semanticObject); 
				return; 
			case ResumeDslPackage.USERDATA:
				sequence_Userdata(context, (Userdata) semanticObject); 
				return; 
			}
		if (errorAcceptor != null)
			errorAcceptor.accept(diagnosticProvider.createInvalidContextOrTypeDiagnostic(semanticObject, context));
	}
	
	/**
	 * <pre>
	 * Contexts:
	 *     Customization returns Customization
	 *
	 * Constraint:
	 *     (language=STRING rules+=Rule*)
	 * </pre>
	 */
	protected void sequence_Customization(ISerializationContext context, Customization semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Degree returns Degree
	 *
	 * Constraint:
	 *     (title=STRING institution=STRING graduationDate=Date country=STRING tags=StringList)
	 * </pre>
	 */
	protected void sequence_Degree(ISerializationContext context, Degree semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, ResumeDslPackage.Literals.DEGREE__TITLE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, ResumeDslPackage.Literals.DEGREE__TITLE));
			if (transientValues.isValueTransient(semanticObject, ResumeDslPackage.Literals.DEGREE__INSTITUTION) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, ResumeDslPackage.Literals.DEGREE__INSTITUTION));
			if (transientValues.isValueTransient(semanticObject, ResumeDslPackage.Literals.DEGREE__GRADUATION_DATE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, ResumeDslPackage.Literals.DEGREE__GRADUATION_DATE));
			if (transientValues.isValueTransient(semanticObject, ResumeDslPackage.Literals.DEGREE__COUNTRY) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, ResumeDslPackage.Literals.DEGREE__COUNTRY));
			if (transientValues.isValueTransient(semanticObject, ResumeDslPackage.Literals.DEGREE__TAGS) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, ResumeDslPackage.Literals.DEGREE__TAGS));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getDegreeAccess().getTitleSTRINGTerminalRuleCall_1_0(), semanticObject.getTitle());
		feeder.accept(grammarAccess.getDegreeAccess().getInstitutionSTRINGTerminalRuleCall_3_0(), semanticObject.getInstitution());
		feeder.accept(grammarAccess.getDegreeAccess().getGraduationDateDateParserRuleCall_5_0(), semanticObject.getGraduationDate());
		feeder.accept(grammarAccess.getDegreeAccess().getCountrySTRINGTerminalRuleCall_7_0(), semanticObject.getCountry());
		feeder.accept(grammarAccess.getDegreeAccess().getTagsStringListParserRuleCall_9_0(), semanticObject.getTags());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Section returns Education
	 *     Education returns Education
	 *
	 * Constraint:
	 *     (language=STRING degrees+=Degree*)
	 * </pre>
	 */
	protected void sequence_Education(ISerializationContext context, Education semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Section returns Experience
	 *     Experience returns Experience
	 *
	 * Constraint:
	 *     (language=STRING jobs+=Job+)
	 * </pre>
	 */
	protected void sequence_Experience(ISerializationContext context, Experience semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Filter returns GeneralFilter
	 *     GeneralFilter returns GeneralFilter
	 *
	 * Constraint:
	 *     tag=STRING
	 * </pre>
	 */
	protected void sequence_GeneralFilter(ISerializationContext context, GeneralFilter semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, ResumeDslPackage.Literals.GENERAL_FILTER__TAG) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, ResumeDslPackage.Literals.GENERAL_FILTER__TAG));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getGeneralFilterAccess().getTagSTRINGTerminalRuleCall_2_0(), semanticObject.getTag());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Section returns Interests
	 *     Interests returns Interests
	 *
	 * Constraint:
	 *     (language=STRING tags=StringList)
	 * </pre>
	 */
	protected void sequence_Interests(ISerializationContext context, Interests semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, ResumeDslPackage.Literals.SECTION__LANGUAGE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, ResumeDslPackage.Literals.SECTION__LANGUAGE));
			if (transientValues.isValueTransient(semanticObject, ResumeDslPackage.Literals.INTERESTS__TAGS) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, ResumeDslPackage.Literals.INTERESTS__TAGS));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getInterestsAccess().getLanguageSTRINGTerminalRuleCall_2_0(), semanticObject.getLanguage());
		feeder.accept(grammarAccess.getInterestsAccess().getTagsStringListParserRuleCall_4_0(), semanticObject.getTags());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Job returns Job
	 *
	 * Constraint:
	 *     (
	 *         title=STRING 
	 *         description=StringList 
	 *         company=STRING 
	 *         startDate=Date 
	 *         endDate=Date 
	 *         tags=StringList
	 *     )
	 * </pre>
	 */
	protected void sequence_Job(ISerializationContext context, Job semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, ResumeDslPackage.Literals.JOB__TITLE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, ResumeDslPackage.Literals.JOB__TITLE));
			if (transientValues.isValueTransient(semanticObject, ResumeDslPackage.Literals.JOB__DESCRIPTION) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, ResumeDslPackage.Literals.JOB__DESCRIPTION));
			if (transientValues.isValueTransient(semanticObject, ResumeDslPackage.Literals.JOB__COMPANY) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, ResumeDslPackage.Literals.JOB__COMPANY));
			if (transientValues.isValueTransient(semanticObject, ResumeDslPackage.Literals.JOB__START_DATE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, ResumeDslPackage.Literals.JOB__START_DATE));
			if (transientValues.isValueTransient(semanticObject, ResumeDslPackage.Literals.JOB__END_DATE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, ResumeDslPackage.Literals.JOB__END_DATE));
			if (transientValues.isValueTransient(semanticObject, ResumeDslPackage.Literals.JOB__TAGS) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, ResumeDslPackage.Literals.JOB__TAGS));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getJobAccess().getTitleSTRINGTerminalRuleCall_1_0(), semanticObject.getTitle());
		feeder.accept(grammarAccess.getJobAccess().getDescriptionStringListParserRuleCall_3_0(), semanticObject.getDescription());
		feeder.accept(grammarAccess.getJobAccess().getCompanySTRINGTerminalRuleCall_5_0(), semanticObject.getCompany());
		feeder.accept(grammarAccess.getJobAccess().getStartDateDateParserRuleCall_7_0(), semanticObject.getStartDate());
		feeder.accept(grammarAccess.getJobAccess().getEndDateDateParserRuleCall_9_0(), semanticObject.getEndDate());
		feeder.accept(grammarAccess.getJobAccess().getTagsStringListParserRuleCall_11_0(), semanticObject.getTags());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Section returns Languages
	 *     Languages returns Languages
	 *
	 * Constraint:
	 *     (language=STRING tags=StringList)
	 * </pre>
	 */
	protected void sequence_Languages(ISerializationContext context, Languages semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, ResumeDslPackage.Literals.SECTION__LANGUAGE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, ResumeDslPackage.Literals.SECTION__LANGUAGE));
			if (transientValues.isValueTransient(semanticObject, ResumeDslPackage.Literals.LANGUAGES__TAGS) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, ResumeDslPackage.Literals.LANGUAGES__TAGS));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getLanguagesAccess().getLanguageSTRINGTerminalRuleCall_2_0(), semanticObject.getLanguage());
		feeder.accept(grammarAccess.getLanguagesAccess().getTagsStringListParserRuleCall_4_0(), semanticObject.getTags());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Metadata returns Metadata
	 *
	 * Constraint:
	 *     (style=STRING font=STRING imgPath=STRING)
	 * </pre>
	 */
	protected void sequence_Metadata(ISerializationContext context, Metadata semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, ResumeDslPackage.Literals.METADATA__STYLE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, ResumeDslPackage.Literals.METADATA__STYLE));
			if (transientValues.isValueTransient(semanticObject, ResumeDslPackage.Literals.METADATA__FONT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, ResumeDslPackage.Literals.METADATA__FONT));
			if (transientValues.isValueTransient(semanticObject, ResumeDslPackage.Literals.METADATA__IMG_PATH) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, ResumeDslPackage.Literals.METADATA__IMG_PATH));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getMetadataAccess().getStyleSTRINGTerminalRuleCall_2_0(), semanticObject.getStyle());
		feeder.accept(grammarAccess.getMetadataAccess().getFontSTRINGTerminalRuleCall_4_0(), semanticObject.getFont());
		feeder.accept(grammarAccess.getMetadataAccess().getImgPathSTRINGTerminalRuleCall_6_0(), semanticObject.getImgPath());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Profile returns Profile
	 *
	 * Constraint:
	 *     (metadata=Metadata userdata=Userdata sections+=Section+ customization=Customization)
	 * </pre>
	 */
	protected void sequence_Profile(ISerializationContext context, Profile semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Project returns Project
	 *
	 * Constraint:
	 *     (title=STRING description=StringList technologies=StringList link=STRING tags=StringList)
	 * </pre>
	 */
	protected void sequence_Project(ISerializationContext context, Project semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, ResumeDslPackage.Literals.PROJECT__TITLE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, ResumeDslPackage.Literals.PROJECT__TITLE));
			if (transientValues.isValueTransient(semanticObject, ResumeDslPackage.Literals.PROJECT__DESCRIPTION) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, ResumeDslPackage.Literals.PROJECT__DESCRIPTION));
			if (transientValues.isValueTransient(semanticObject, ResumeDslPackage.Literals.PROJECT__TECHNOLOGIES) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, ResumeDslPackage.Literals.PROJECT__TECHNOLOGIES));
			if (transientValues.isValueTransient(semanticObject, ResumeDslPackage.Literals.PROJECT__LINK) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, ResumeDslPackage.Literals.PROJECT__LINK));
			if (transientValues.isValueTransient(semanticObject, ResumeDslPackage.Literals.PROJECT__TAGS) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, ResumeDslPackage.Literals.PROJECT__TAGS));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getProjectAccess().getTitleSTRINGTerminalRuleCall_1_0(), semanticObject.getTitle());
		feeder.accept(grammarAccess.getProjectAccess().getDescriptionStringListParserRuleCall_3_0(), semanticObject.getDescription());
		feeder.accept(grammarAccess.getProjectAccess().getTechnologiesStringListParserRuleCall_5_0(), semanticObject.getTechnologies());
		feeder.accept(grammarAccess.getProjectAccess().getLinkSTRINGTerminalRuleCall_7_0(), semanticObject.getLink());
		feeder.accept(grammarAccess.getProjectAccess().getTagsStringListParserRuleCall_9_0(), semanticObject.getTags());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Section returns Projects
	 *     Projects returns Projects
	 *
	 * Constraint:
	 *     (language=STRING projects+=Project+)
	 * </pre>
	 */
	protected void sequence_Projects(ISerializationContext context, Projects semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Rule returns Rule
	 *
	 * Constraint:
	 *     (sectionType=SectionType filter=Filter)
	 * </pre>
	 */
	protected void sequence_Rule(ISerializationContext context, Rule semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, ResumeDslPackage.Literals.RULE__SECTION_TYPE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, ResumeDslPackage.Literals.RULE__SECTION_TYPE));
			if (transientValues.isValueTransient(semanticObject, ResumeDslPackage.Literals.RULE__FILTER) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, ResumeDslPackage.Literals.RULE__FILTER));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getRuleAccess().getSectionTypeSectionTypeEnumRuleCall_1_0(), semanticObject.getSectionType());
		feeder.accept(grammarAccess.getRuleAccess().getFilterFilterParserRuleCall_3_0(), semanticObject.getFilter());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Skill returns Skill
	 *
	 * Constraint:
	 *     (title=STRING tags=StringList)
	 * </pre>
	 */
	protected void sequence_Skill(ISerializationContext context, Skill semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, ResumeDslPackage.Literals.SKILL__TITLE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, ResumeDslPackage.Literals.SKILL__TITLE));
			if (transientValues.isValueTransient(semanticObject, ResumeDslPackage.Literals.SKILL__TAGS) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, ResumeDslPackage.Literals.SKILL__TAGS));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getSkillAccess().getTitleSTRINGTerminalRuleCall_1_0(), semanticObject.getTitle());
		feeder.accept(grammarAccess.getSkillAccess().getTagsStringListParserRuleCall_3_0(), semanticObject.getTags());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Section returns Skills
	 *     Skills returns Skills
	 *
	 * Constraint:
	 *     (language=STRING skills+=Skill+)
	 * </pre>
	 */
	protected void sequence_Skills(ISerializationContext context, Skills semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     StringList returns StringList
	 *
	 * Constraint:
	 *     (values+=STRING values+=STRING*)
	 * </pre>
	 */
	protected void sequence_StringList(ISerializationContext context, StringList semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Filter returns TemporalFilter
	 *     TemporalFilter returns TemporalFilter
	 *
	 * Constraint:
	 *     (startDate=Date | endDate=Date)
	 * </pre>
	 */
	protected void sequence_TemporalFilter(ISerializationContext context, TemporalFilter semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Userdata returns Userdata
	 *
	 * Constraint:
	 *     (
	 *         name=STRING 
	 *         email=STRING 
	 *         telephoneNumber=STRING 
	 *         direction=STRING 
	 *         city=STRING 
	 *         country=STRING
	 *     )
	 * </pre>
	 */
	protected void sequence_Userdata(ISerializationContext context, Userdata semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, ResumeDslPackage.Literals.USERDATA__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, ResumeDslPackage.Literals.USERDATA__NAME));
			if (transientValues.isValueTransient(semanticObject, ResumeDslPackage.Literals.USERDATA__EMAIL) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, ResumeDslPackage.Literals.USERDATA__EMAIL));
			if (transientValues.isValueTransient(semanticObject, ResumeDslPackage.Literals.USERDATA__TELEPHONE_NUMBER) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, ResumeDslPackage.Literals.USERDATA__TELEPHONE_NUMBER));
			if (transientValues.isValueTransient(semanticObject, ResumeDslPackage.Literals.USERDATA__DIRECTION) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, ResumeDslPackage.Literals.USERDATA__DIRECTION));
			if (transientValues.isValueTransient(semanticObject, ResumeDslPackage.Literals.USERDATA__CITY) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, ResumeDslPackage.Literals.USERDATA__CITY));
			if (transientValues.isValueTransient(semanticObject, ResumeDslPackage.Literals.USERDATA__COUNTRY) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, ResumeDslPackage.Literals.USERDATA__COUNTRY));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getUserdataAccess().getNameSTRINGTerminalRuleCall_2_0(), semanticObject.getName());
		feeder.accept(grammarAccess.getUserdataAccess().getEmailSTRINGTerminalRuleCall_4_0(), semanticObject.getEmail());
		feeder.accept(grammarAccess.getUserdataAccess().getTelephoneNumberSTRINGTerminalRuleCall_6_0(), semanticObject.getTelephoneNumber());
		feeder.accept(grammarAccess.getUserdataAccess().getDirectionSTRINGTerminalRuleCall_8_0(), semanticObject.getDirection());
		feeder.accept(grammarAccess.getUserdataAccess().getCitySTRINGTerminalRuleCall_10_0(), semanticObject.getCity());
		feeder.accept(grammarAccess.getUserdataAccess().getCountrySTRINGTerminalRuleCall_12_0(), semanticObject.getCountry());
		feeder.finish();
	}
	
	
}
