/*
 * generated by Xtext 2.40.0
 */
package org.example.dsl.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.example.dsl.parser.antlr.internal.InternalResumeDslParser;
import org.example.dsl.services.ResumeDslGrammarAccess;

public class ResumeDslParser extends AbstractAntlrParser {

	@Inject
	private ResumeDslGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalResumeDslParser createParser(XtextTokenStream stream) {
		return new InternalResumeDslParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Profile";
	}

	public ResumeDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(ResumeDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
