/*
 * generated by Xtext 2.40.0
 */
package org.example.dsl.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.example.dsl.ResumeDslRuntimeModule;
import org.example.dsl.ResumeDslStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class ResumeDslIdeSetup extends ResumeDslStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new ResumeDslRuntimeModule(), new ResumeDslIdeModule()));
	}
	
}
