/**
 * generated by Xtext 2.40.0
 */
package org.example.dsl.resumeDsl;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Education</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.example.dsl.resumeDsl.Education#getDegrees <em>Degrees</em>}</li>
 * </ul>
 *
 * @see org.example.dsl.resumeDsl.ResumeDslPackage#getEducation()
 * @model
 * @generated
 */
public interface Education extends Section
{
  /**
   * Returns the value of the '<em><b>Degrees</b></em>' containment reference list.
   * The list contents are of type {@link org.example.dsl.resumeDsl.Degree}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Degrees</em>' containment reference list.
   * @see org.example.dsl.resumeDsl.ResumeDslPackage#getEducation_Degrees()
   * @model containment="true"
   * @generated
   */
  EList<Degree> getDegrees();

} // Education
