/**
 * generated by Xtext 2.40.0
 */
package org.example.dsl.resumeDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Filter</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.example.dsl.resumeDsl.ResumeDslPackage#getFilter()
 * @model
 * @generated
 */
public interface Filter extends EObject
{
} // Filter
