/**
 * generated by Xtext 2.40.0
 */
package org.example.dsl.resumeDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Metadata</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.example.dsl.resumeDsl.Metadata#getStyle <em>Style</em>}</li>
 *   <li>{@link org.example.dsl.resumeDsl.Metadata#getFont <em>Font</em>}</li>
 *   <li>{@link org.example.dsl.resumeDsl.Metadata#getImgPath <em>Img Path</em>}</li>
 * </ul>
 *
 * @see org.example.dsl.resumeDsl.ResumeDslPackage#getMetadata()
 * @model
 * @generated
 */
public interface Metadata extends EObject
{
  /**
   * Returns the value of the '<em><b>Style</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Style</em>' attribute.
   * @see #setStyle(String)
   * @see org.example.dsl.resumeDsl.ResumeDslPackage#getMetadata_Style()
   * @model
   * @generated
   */
  String getStyle();

  /**
   * Sets the value of the '{@link org.example.dsl.resumeDsl.Metadata#getStyle <em>Style</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Style</em>' attribute.
   * @see #getStyle()
   * @generated
   */
  void setStyle(String value);

  /**
   * Returns the value of the '<em><b>Font</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Font</em>' attribute.
   * @see #setFont(String)
   * @see org.example.dsl.resumeDsl.ResumeDslPackage#getMetadata_Font()
   * @model
   * @generated
   */
  String getFont();

  /**
   * Sets the value of the '{@link org.example.dsl.resumeDsl.Metadata#getFont <em>Font</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Font</em>' attribute.
   * @see #getFont()
   * @generated
   */
  void setFont(String value);

  /**
   * Returns the value of the '<em><b>Img Path</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Img Path</em>' attribute.
   * @see #setImgPath(String)
   * @see org.example.dsl.resumeDsl.ResumeDslPackage#getMetadata_ImgPath()
   * @model
   * @generated
   */
  String getImgPath();

  /**
   * Sets the value of the '{@link org.example.dsl.resumeDsl.Metadata#getImgPath <em>Img Path</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Img Path</em>' attribute.
   * @see #getImgPath()
   * @generated
   */
  void setImgPath(String value);

} // Metadata
