/**
 * generated by Xtext 2.40.0
 */
package org.example.dsl.resumeDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Profile</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.example.dsl.resumeDsl.Profile#getMetadata <em>Metadata</em>}</li>
 *   <li>{@link org.example.dsl.resumeDsl.Profile#getUserdata <em>Userdata</em>}</li>
 *   <li>{@link org.example.dsl.resumeDsl.Profile#getSections <em>Sections</em>}</li>
 *   <li>{@link org.example.dsl.resumeDsl.Profile#getCustomization <em>Customization</em>}</li>
 * </ul>
 *
 * @see org.example.dsl.resumeDsl.ResumeDslPackage#getProfile()
 * @model
 * @generated
 */
public interface Profile extends EObject
{
  /**
   * Returns the value of the '<em><b>Metadata</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Metadata</em>' containment reference.
   * @see #setMetadata(Metadata)
   * @see org.example.dsl.resumeDsl.ResumeDslPackage#getProfile_Metadata()
   * @model containment="true"
   * @generated
   */
  Metadata getMetadata();

  /**
   * Sets the value of the '{@link org.example.dsl.resumeDsl.Profile#getMetadata <em>Metadata</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Metadata</em>' containment reference.
   * @see #getMetadata()
   * @generated
   */
  void setMetadata(Metadata value);

  /**
   * Returns the value of the '<em><b>Userdata</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Userdata</em>' containment reference.
   * @see #setUserdata(Userdata)
   * @see org.example.dsl.resumeDsl.ResumeDslPackage#getProfile_Userdata()
   * @model containment="true"
   * @generated
   */
  Userdata getUserdata();

  /**
   * Sets the value of the '{@link org.example.dsl.resumeDsl.Profile#getUserdata <em>Userdata</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Userdata</em>' containment reference.
   * @see #getUserdata()
   * @generated
   */
  void setUserdata(Userdata value);

  /**
   * Returns the value of the '<em><b>Sections</b></em>' containment reference list.
   * The list contents are of type {@link org.example.dsl.resumeDsl.Section}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Sections</em>' containment reference list.
   * @see org.example.dsl.resumeDsl.ResumeDslPackage#getProfile_Sections()
   * @model containment="true"
   * @generated
   */
  EList<Section> getSections();

  /**
   * Returns the value of the '<em><b>Customization</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Customization</em>' containment reference.
   * @see #setCustomization(Customization)
   * @see org.example.dsl.resumeDsl.ResumeDslPackage#getProfile_Customization()
   * @model containment="true"
   * @generated
   */
  Customization getCustomization();

  /**
   * Sets the value of the '{@link org.example.dsl.resumeDsl.Profile#getCustomization <em>Customization</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Customization</em>' containment reference.
   * @see #getCustomization()
   * @generated
   */
  void setCustomization(Customization value);

} // Profile
