/**
 * generated by Xtext 2.40.0
 */
package org.example.dsl.resumeDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Rule</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.example.dsl.resumeDsl.Rule#getSectionType <em>Section Type</em>}</li>
 *   <li>{@link org.example.dsl.resumeDsl.Rule#getFilter <em>Filter</em>}</li>
 * </ul>
 *
 * @see org.example.dsl.resumeDsl.ResumeDslPackage#getRule()
 * @model
 * @generated
 */
public interface Rule extends EObject
{
  /**
   * Returns the value of the '<em><b>Section Type</b></em>' attribute.
   * The literals are from the enumeration {@link org.example.dsl.resumeDsl.SectionType}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Section Type</em>' attribute.
   * @see org.example.dsl.resumeDsl.SectionType
   * @see #setSectionType(SectionType)
   * @see org.example.dsl.resumeDsl.ResumeDslPackage#getRule_SectionType()
   * @model
   * @generated
   */
  SectionType getSectionType();

  /**
   * Sets the value of the '{@link org.example.dsl.resumeDsl.Rule#getSectionType <em>Section Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Section Type</em>' attribute.
   * @see org.example.dsl.resumeDsl.SectionType
   * @see #getSectionType()
   * @generated
   */
  void setSectionType(SectionType value);

  /**
   * Returns the value of the '<em><b>Filter</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Filter</em>' containment reference.
   * @see #setFilter(Filter)
   * @see org.example.dsl.resumeDsl.ResumeDslPackage#getRule_Filter()
   * @model containment="true"
   * @generated
   */
  Filter getFilter();

  /**
   * Sets the value of the '{@link org.example.dsl.resumeDsl.Rule#getFilter <em>Filter</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Filter</em>' containment reference.
   * @see #getFilter()
   * @generated
   */
  void setFilter(Filter value);

} // Rule
