/**
 * generated by Xtext 2.40.0
 */
package org.example.dsl.resumeDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Skill</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.example.dsl.resumeDsl.Skill#getTitle <em>Title</em>}</li>
 *   <li>{@link org.example.dsl.resumeDsl.Skill#getTags <em>Tags</em>}</li>
 * </ul>
 *
 * @see org.example.dsl.resumeDsl.ResumeDslPackage#getSkill()
 * @model
 * @generated
 */
public interface Skill extends EObject
{
  /**
   * Returns the value of the '<em><b>Title</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Title</em>' attribute.
   * @see #setTitle(String)
   * @see org.example.dsl.resumeDsl.ResumeDslPackage#getSkill_Title()
   * @model
   * @generated
   */
  String getTitle();

  /**
   * Sets the value of the '{@link org.example.dsl.resumeDsl.Skill#getTitle <em>Title</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Title</em>' attribute.
   * @see #getTitle()
   * @generated
   */
  void setTitle(String value);

  /**
   * Returns the value of the '<em><b>Tags</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Tags</em>' containment reference.
   * @see #setTags(StringList)
   * @see org.example.dsl.resumeDsl.ResumeDslPackage#getSkill_Tags()
   * @model containment="true"
   * @generated
   */
  StringList getTags();

  /**
   * Sets the value of the '{@link org.example.dsl.resumeDsl.Skill#getTags <em>Tags</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Tags</em>' containment reference.
   * @see #getTags()
   * @generated
   */
  void setTags(StringList value);

} // Skill
