/**
 * generated by Xtext 2.40.0
 */
package org.example.dsl.resumeDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>String List</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.example.dsl.resumeDsl.StringList#getValues <em>Values</em>}</li>
 * </ul>
 *
 * @see org.example.dsl.resumeDsl.ResumeDslPackage#getStringList()
 * @model
 * @generated
 */
public interface StringList extends EObject
{
  /**
   * Returns the value of the '<em><b>Values</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Values</em>' attribute list.
   * @see org.example.dsl.resumeDsl.ResumeDslPackage#getStringList_Values()
   * @model unique="false"
   * @generated
   */
  EList<String> getValues();

} // StringList
